# Based off https://github.com/Azure/bicep/blob/main/.pipelines/Common.yml
stages:
  - stage: build
    jobs:
      - job: windows
        pool:
          vmImage: "windows-latest"

        variables:
          ob_outputDirectory: "$(Build.SourcesDirectory)/out"
        steps:
          - template: BuildCli.yml
            parameters:
              rid: win-x64

      - job: linux
        pool:
          vmImage: "ubuntu-latest"

        variables:
          ob_outputDirectory: "$(Build.SourcesDirectory)/out" # this directory is uploaded to pipeline artifacts, reddog and cloudvault. More info at https://aka.ms/obpipelines/artifacts

        steps:
          - template: BuildCli.yml
            parameters:
              rid: linux-x64

      - job: linux_musl
        pool:
          vmImage: "ubuntu-latest"

        variables:
          ob_outputDirectory: "$(Build.SourcesDirectory)/out" # this directory is uploaded to pipeline artifacts, reddog and cloudvault. More info at https://aka.ms/obpipelines/artifacts
        steps:
          - template: BuildCli.yml
            parameters:
              rid: linux-musl-x64

      - job: osx
        pool:
          vmImage: "macOS-latest"

        variables:
          ob_outputDirectory: "$(Build.SourcesDirectory)/out" # this directory is uploaded to pipeline artifacts, reddog and cloudvault. More info at https://aka.ms/obpipelines/artifacts
        steps:
          - template: BuildCli.yml
            parameters:
              rid: osx-x64
