#################################################################################
# Based off : https://github.com/Azure/bicep/blob/main/.pipelines/OneBranch.Official.yml 
#################################################################################

# https://aka.ms/obpipelines/triggers
trigger:
  batch: true
  branches:
    include:
      - master

parameters: # parameters are shown up in ADO UI in a build queue time
- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false

variables:
  system.debug: ${{ parameters.debug }}

  BuildSolution: $(Build.SourcesDirectory)/kaalsaas.Arm.Parameters.sln
  BuildConfiguration: Release
  TargetFramework: net5.0


resources:
  repositories: 
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

    stages:
    - template: Common.yml
